version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./www/vue:/www
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - range
  php-fpm:
    # image: php:8.0.12
    build: ./dockerfile/php:8.0.12
    container_name: php8
    privileged: true
    expose:
      - "9000"
    volumes:
      - ./www/php:/www
      - ./php/config:/usr/local/etc/php
    environment:
      - TZ=Asia/Shanghai
    networks:
      - range
  mysql:
    image: mysql:8.0
    container_name: mysql8
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=range
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Asia/Shanghai
    networks:
      - range
networks:
  range: